### ISSUE TITLE
Bug: Script is giving warning for set output.

### ISSUE THREAD

**Issue by danishedb** [Azure/setup-helm#103]
### What happened?

Helm tool version: 'v3.10.2' has been cached at /opt/hostedtoolcache/helm/3.10.2/x64/linux-amd64/helm
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Version

- [X] I am using the latest version

### Runner

github action

### Relevant log output

Helm tool version: 'v3.10.2' has been cached at /opt/hostedtoolcache/helm/3.10.2/x64/linux-amd64/helm
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by harikrishnatrkv** [comment]
I am  facing the same issue. It giving the warning message as follows.


`Run azure/setup-helm@v1
/usr/bin/unzip /home/runner/work/_temp/1c89de15-9805-43ee-b38a-e270731c9ec6
Archive:  /home/runner/work/_temp/1c89de15-9805-43ee-b38a-e270731c9ec6
   creating: linux-amd64/
  inflating: linux-amd64/helm        
  inflating: linux-amd64/LICENSE     
  inflating: linux-amd64/README.md   
Helm tool version: 'v3.7.2' has been cached at /opt/hostedtoolcache/helm/3.7.2/x64/linux-amd64/helm
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`


Please help

**Comment by OliverMKing** [comment]
Hello! This has been fixed and was released in `v3.5` (and `v3`). Thanks for the issue!
