### ISSUE TITLE
be able to install latest v2 or latest v3

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/setup-helm#12]
the 'latest' will pick whatever helm release was done last, either it's v2 or v3. It would be useful to define version as "latest v2" or "latest v3".

**Comment by shigupt202** [comment]
@davidkarlsen Thanks for the feedback. I've raised a PR to fix this, so that the action downloads latest version and not the last updated version of Helm release.

**Comment by ds-ms** [comment]
@shigupt202 I believe this is a different ask, in parallel to your fix.

**Comment by anraghun** [comment]
@ds-ms We can have a delimiter separated input for the major version if latest is supplied as version such as `latest;3` or `latest:2`. The logic can be modified to see if `version.toLocaleLowerCase()` contains "latest" and then probe for the additional major version.

**Comment by ds-ms** [comment]
@anraghun as discussed offline, we'll go ahead with `2.*` and `3.*` for getting the latest major version change.

@shigupt202 do you want to pick up this change?

**Comment by shigupt202** [comment]
Sure

**Comment by ds-ms** [comment]
@shigupt202 any updates on this?

**Comment by shigupt202** [comment]
This feature has been released. Latest Helm 3 versions can be specified using `3.*` and Helm 2 versions using `2.*`.
