### ISSUE TITLE
Update tag

### ISSUE THREAD

**Issue by felipecrs** [Azure/setup-helm#33]
Hey, could you please update the `v1` tag?

```sh-session
git tag -f v1 v1.1
git push --force origin v1
```

https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

References https://github.com/felipecrs/megatar/pull/202

**Comment by shigupt202** [comment]
@ds-ms The convention that we decided to follow seems to be different from what's been given in the mentioned link.

**Comment by shigupt202** [comment]
Updated the v1 tag to latest commit!

**Comment by felipecrs** [comment]
Awesome, thank you so much.
