### ISSUE TITLE
Checksum validation

### ISSUE THREAD

**Issue by tomarrell** [Azure/setup-helm#37]
I noticed that the download of the binaries omits checksum validation.

The checksums for the binaries are published on the same path with a `.sha256sum` extension, e.g. https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz.sha256sum.

Would be great just for extra security to validate the sums after download.

**Comment by ds-ms** [comment]
@tomarrell would you be willing to raise a PR for the same?

**Comment by tomarrell** [comment]
@ds-ms I'm afraid I don't quite have the time these days. If things settle down I can take a look, but I wouldn't hold your breath 😓

**Comment by shigupt202** [comment]
There's a similar [issue](https://github.com/actions/toolkit/issues/427) open on toolkit repo as well. It makes sense to have this validation on the upstream tool. Once that is done, we can incorporate in our actions as well. Closing this issue for now.
