### ISSUE TITLE
Option for installing tiller

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/setup-helm#4]
It would be great if the action could [optionally] installer tiller too. That would be a good fit for builds based on kinD where you don't have an existing cluster where tiller could be expected to already be running.

**Comment by ds-ms** [comment]
@davidkarlsen you could always install tiller by running the `helm init` command if you're using a `2.x` version of helm in your workflow, right?

**Comment by davidkarlsen** [comment]
Sure. Then I need the binary accessible. However I found an action which solves helm ++ so this is no longer a problem

**Comment by ds-ms** [comment]
The binary is added to the path; so it is accessible or you could use the output variable as well which is being exposed in the action for the same.
