### ISSUE TITLE
Support for different architectures

### ISSUE THREAD

**Issue by michael-baraboo-cnr** [Azure/setup-helm#53]
Hello, and thanks for the useful action.

It seems this action currently only supports amd64, which appears to be hardcoded in the get.helm.sh url.
https://github.com/Azure/setup-helm/blob/master/lib/run.js#L59

It would be nice to have this support alternative architectures such as arm64 the same way the azure/setup-kubectl action does.

Currently working around this by copying a lot of the same logic in bash.
```
             mkdir -p /tmp/helm /opt/hostedtoolcache/helm/3.7.2/arm64/linux-arm64/
             wget https://get.helm.sh/helm-v3.7.2-linux-arm64.tar.gz
             tar -zxvf helm-v3.7.2-linux-arm64.tar.gz -C /tmp/helm
             mv /tmp/helm/linux-arm64/helm /opt/hostedtoolcache/helm/3.7.2/arm64/linux-arm64/
             echo "/opt/hostedtoolcache/helm/3.7.2/arm64/linux-arm64/" >> $GITHUB_PATH
```

**Comment by qpetraroia** [comment]
Hey @michael-baraboo-cnr,

For sure, we will look into this! This is in the pipeline!
