### ISSUE TITLE
version-range does not work with v2

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/setup-helm#58]
see: https://github.com/evryfs/helm-charts/runs/4962602955?check_suite_focus=true
```
Run azure/setup-helm@v2.0
  with:
    version: 3.*
Error: Error: Failed to download Helm from location get.helm.sh/helm-3.*-linux-amd64.zip
```

**Comment by podollb** [comment]
nothing works; even explicit version doesn't work...
```
with:
  version: 3.8.8
```

**Comment by qpetraroia** [comment]
Hey @davidkarlsen, 

The URL is not pointing to a valid resource, we are looking into it.

**Comment by OliverMKing** [comment]
Hello! Version ranges are not supported in v2. You can use "latest" if you want the most recent version. Helm2 is also not supported in v2 of this action. 


> nothing works; even explicit version doesn't work...
> 
> I tried with:
> 
> ```
> with:
>   version: 3.7.2
> ```
> 
> and
> 
> ```
> with:
>   version: 3.8.0
> ```

This didn't work because a v was required. We pushed an improvement that prepends a 'v' if one isn't given so this should work now.
