### ISSUE TITLE
Bug: Latest version is grabbing alpha version of tool

### ISSUE THREAD

**Issue by KenBurk** [Azure/setup-helm#97]
### What happened?

Expecting:
Helm tool version: '**v3.8.2**' has been cached at /opt/hostedtoolcache/helm/3.8.2/x64/linux-amd64/helm
actual
Helm tool version: '**v3.0.0-alpha.1**' has been cached at /opt/hostedtoolcache/helm/3.0.0-alpha.1/x64/linux-amd64/helm

### Version

- [X] I am using the latest version

### Runner

self-hosted

### Relevant log output

Run azure/setup-helm@v1
  with:
    version: latest
...
   creating: linux-amd64/
  inflating: linux-amd64/helm        
  inflating: linux-amd64/LICENSE     
  inflating: linux-amd64/README.md

**Comment by kxiao-msk** [comment]
we face the same issue, can this be fixed ASAP?

**Comment by ShiroTian** [comment]
me too

**Comment by umutkacar** [comment]
We were using `azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1` and we also encountered this issue.

It was installing an alpha version: `Helm tool version: 'v3.0.0-alpha.1' has been cached at /opt/hostedtoolcache/helm/3.0.0-alpha.1/x64/linux-amd64/helm`

Switching to `azure/setup-helm@20d2b4f98d41febe2bbca46408499dbb535b6258 # v3.0` seems to have fixed the issue.

I need to observe a little more to confirm.

**Comment by OliverMKing** [comment]
This will be fixed in #100. I'm going to roll it out as soon as possible. #98 and #99 are duplicates of this.

**Comment by OliverMKing** [comment]
This has been fixed and released in v3.4 (and v3). Please upgrade to one of these versions. Thanks!
